ALTER TABLE `UsersDesktop` ADD COLUMN `Email` VARCHAR(255) NULL;
ALTER TABLE `SaleTicketItemDesktop` ADD COLUMN `ClassSaleId` VARCHAR(36) NULL;

CREATE TABLE `AccessUsersDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  `Pin` VARCHAR(100) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `CardNo` VARCHAR(100) NULL,
  `Enabled` TINYINT NOT NULL DEFAULT 1,
  `CreatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Sync` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_AccessUsersDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_AccessUsersDesktop_UserId` (`UserId`),
  CONSTRAINT `fk_AccessUsersDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_AccessUsersDesktop_UserId` FOREIGN KEY (`UserId`) REFERENCES `UsersDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassCatalogDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `NameSearch` VARCHAR(255) NULL,
  `Description` TEXT NULL,
  `Active` TINYINT NOT NULL DEFAULT 1,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassCatalogDesktop_CustomerApiId` (`CustomerApiId`),
  CONSTRAINT `fk_ClassCatalogDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `InstructorsDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `FullName` VARCHAR(255) NOT NULL,
  `FullNameSearch` VARCHAR(255) NULL,
  `Email` VARCHAR(255) NULL,
  `PhoneNumber` VARCHAR(50) NULL,
  `Notes` TEXT NULL,
  `Active` TINYINT NOT NULL DEFAULT 1,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_InstructorsDesktop_CustomerApiId` (`CustomerApiId`),
  CONSTRAINT `fk_InstructorsDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassInstructorsDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `ClassId` VARCHAR(36) NOT NULL,
  `InstructorId` VARCHAR(36) NOT NULL,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassInstructorsDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_ClassInstructorsDesktop_ClassId` (`ClassId`),
  INDEX `idx_ClassInstructorsDesktop_InstructorId` (`InstructorId`),
  CONSTRAINT `fk_ClassInstructorsDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassInstructorsDesktop_InstructorId` FOREIGN KEY (`InstructorId`) REFERENCES `InstructorsDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassInstructorsDesktop_ClassId` FOREIGN KEY (`ClassId`) REFERENCES `ClassCatalogDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassScheduleGroupsDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `ClassId` VARCHAR(36) NOT NULL,
  `InstructorId` VARCHAR(36) NULL,
  `StartDate` DATETIME NOT NULL,
  `EndDate` DATETIME NOT NULL,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  `DaysOfWeek` VARCHAR(100) NULL,
  `Capacity` INT NOT NULL DEFAULT 0,
  `Price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `Active` TINYINT NOT NULL DEFAULT 1,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassScheduleGroupsDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_ClassScheduleGroupsDesktop_ClassId` (`ClassId`),
  INDEX `idx_ClassScheduleGroupsDesktop_InstructorId` (`InstructorId`),
  CONSTRAINT `fk_ClassScheduleGroupsDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassScheduleGroupsDesktop_InstructorId` FOREIGN KEY (`InstructorId`) REFERENCES `InstructorsDesktop` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `fk_ClassScheduleGroupsDesktop_ClassId` FOREIGN KEY (`ClassId`) REFERENCES `ClassCatalogDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassSchedulesDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `ScheduleGroupId` VARCHAR(36) NULL,
  `ClassId` VARCHAR(36) NOT NULL,
  `InstructorId` VARCHAR(36) NULL,
  `ClassDate` DATETIME NOT NULL,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  `Capacity` INT NOT NULL DEFAULT 0,
  `Price` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `Status` VARCHAR(50) NOT NULL DEFAULT 'Activa',
  `Active` TINYINT NOT NULL DEFAULT 1,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassSchedulesDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_ClassSchedulesDesktop_ScheduleGroupId` (`ScheduleGroupId`),
  INDEX `idx_ClassSchedulesDesktop_ClassId` (`ClassId`),
  INDEX `idx_ClassSchedulesDesktop_InstructorId` (`InstructorId`),
  CONSTRAINT `fk_ClassSchedulesDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassSchedulesDesktop_InstructorId` FOREIGN KEY (`InstructorId`) REFERENCES `InstructorsDesktop` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `fk_ClassSchedulesDesktop_ClassId` FOREIGN KEY (`ClassId`) REFERENCES `ClassCatalogDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassSchedulesDesktop_ScheduleGroupId` FOREIGN KEY (`ScheduleGroupId`) REFERENCES `ClassScheduleGroupsDesktop` (`Id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassEnrollmentsDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `ScheduleGroupId` VARCHAR(36) NULL,
  `ClassId` VARCHAR(36) NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  `Status` VARCHAR(50) NOT NULL,
  `Notes` TEXT NULL,
  `EnrolledOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `RemovedOn` DATETIME NULL,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassEnrollmentsDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_ClassEnrollmentsDesktop_ScheduleGroupId` (`ScheduleGroupId`),
  INDEX `idx_ClassEnrollmentsDesktop_ClassId` (`ClassId`),
  INDEX `idx_ClassEnrollmentsDesktop_UserId` (`UserId`),
  CONSTRAINT `fk_ClassEnrollmentsDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassEnrollmentsDesktop_UserId` FOREIGN KEY (`UserId`) REFERENCES `UsersDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassEnrollmentsDesktop_ClassId` FOREIGN KEY (`ClassId`) REFERENCES `ClassCatalogDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassEnrollmentsDesktop_ScheduleGroupId` FOREIGN KEY (`ScheduleGroupId`) REFERENCES `ClassScheduleGroupsDesktop` (`Id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassReservationsDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `ScheduleId` VARCHAR(36) NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  `Status` VARCHAR(50) NOT NULL,
  `Notes` TEXT NULL,
  `ReservedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CancelledOn` DATETIME NULL,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassReservationsDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_ClassReservationsDesktop_ScheduleId` (`ScheduleId`),
  INDEX `idx_ClassReservationsDesktop_UserId` (`UserId`),
  CONSTRAINT `fk_ClassReservationsDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassReservationsDesktop_UserId` FOREIGN KEY (`UserId`) REFERENCES `UsersDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassReservationsDesktop_ScheduleId` FOREIGN KEY (`ScheduleId`) REFERENCES `ClassSchedulesDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassScheduleInstructorsDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `ClassScheduleId` VARCHAR(36) NOT NULL,
  `ScheduleGroupId` VARCHAR(36) NULL,
  `InstructorId` VARCHAR(36) NOT NULL,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassScheduleInstructorsDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_ClassScheduleInstructorsDesktop_ClassScheduleId` (`ClassScheduleId`),
  INDEX `idx_ClassScheduleInstructorsDesktop_ScheduleGroupId` (`ScheduleGroupId`),
  INDEX `idx_ClassScheduleInstructorsDesktop_InstructorId` (`InstructorId`),
  CONSTRAINT `fk_ClassScheduleInstructorsDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassScheduleInstructorsDesktop_InstructorId` FOREIGN KEY (`InstructorId`) REFERENCES `InstructorsDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassScheduleInstructorsDesktop_ScheduleGroupId` FOREIGN KEY (`ScheduleGroupId`) REFERENCES `ClassScheduleGroupsDesktop` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `fk_ClassScheduleInstructorsDesktop_ClassScheduleId` FOREIGN KEY (`ClassScheduleId`) REFERENCES `ClassSchedulesDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ClassScheduleReschedulesDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `OriginScheduleId` VARCHAR(36) NOT NULL,
  `DestinationScheduleId` VARCHAR(36) NOT NULL,
  `Notes` TEXT NULL,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_ClassScheduleReschedulesDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_ClassScheduleReschedulesDesktop_OriginScheduleId` (`OriginScheduleId`),
  INDEX `idx_ClassScheduleReschedulesDesktop_DestinationScheduleId` (`DestinationScheduleId`),
  CONSTRAINT `fk_ClassScheduleReschedulesDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassScheduleReschedulesDesktop_DestinationScheduleId` FOREIGN KEY (`DestinationScheduleId`) REFERENCES `ClassSchedulesDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ClassScheduleReschedulesDesktop_OriginScheduleId` FOREIGN KEY (`OriginScheduleId`) REFERENCES `ClassSchedulesDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `SaleClassesDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `UserId` VARCHAR(36) NOT NULL,
  `SaleTicketId` VARCHAR(36) NULL,
  `SaleTicketItemId` VARCHAR(36) NULL,
  `SubtotalAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `DiscountAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `TaxAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `TotalAmount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_SaleClassesDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_SaleClassesDesktop_UserId` (`UserId`),
  INDEX `idx_SaleClassesDesktop_SaleTicketId` (`SaleTicketId`),
  INDEX `idx_SaleClassesDesktop_SaleTicketItemId` (`SaleTicketItemId`),
  CONSTRAINT `fk_SaleClassesDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_SaleClassesDesktop_SaleTicketItemId` FOREIGN KEY (`SaleTicketItemId`) REFERENCES `SaleTicketItemDesktop` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `fk_SaleClassesDesktop_SaleTicketId` FOREIGN KEY (`SaleTicketId`) REFERENCES `SaleTicketDesktop` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `fk_SaleClassesDesktop_UserId` FOREIGN KEY (`UserId`) REFERENCES `UsersDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `SaleClassSchedulesDesktop` (
  `Id` VARCHAR(36) NOT NULL,
  `CustomerApiId` VARCHAR(64) NOT NULL,
  `SaleClassId` VARCHAR(36) NOT NULL,
  `ClassScheduleId` VARCHAR(36) NOT NULL,
  `ReservationId` VARCHAR(36) NULL,
  `UnitPrice` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `CreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedBy` VARCHAR(100) NULL,
  `LastModifiedOn` DATETIME NULL,
  `LastModifiedBy` VARCHAR(100) NULL,
  `IsDeleted` TINYINT NOT NULL DEFAULT 0,
  `Sync` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Id`),
  INDEX `idx_SaleClassSchedulesDesktop_CustomerApiId` (`CustomerApiId`),
  INDEX `idx_SaleClassSchedulesDesktop_SaleClassId` (`SaleClassId`),
  INDEX `idx_SaleClassSchedulesDesktop_ClassScheduleId` (`ClassScheduleId`),
  INDEX `idx_SaleClassSchedulesDesktop_ReservationId` (`ReservationId`),
  CONSTRAINT `fk_SaleClassSchedulesDesktop_Customer` FOREIGN KEY (`CustomerApiId`) REFERENCES `Customers` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_SaleClassSchedulesDesktop_ReservationId` FOREIGN KEY (`ReservationId`) REFERENCES `ClassReservationsDesktop` (`Id`) ON DELETE SET NULL,
  CONSTRAINT `fk_SaleClassSchedulesDesktop_ClassScheduleId` FOREIGN KEY (`ClassScheduleId`) REFERENCES `ClassSchedulesDesktop` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `fk_SaleClassSchedulesDesktop_SaleClassId` FOREIGN KEY (`SaleClassId`) REFERENCES `SaleClassesDesktop` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
